_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  announcements_feed: 0
  automatic_updates: 0
  autosave_form: 0
  better_exposed_filters: 0
  block: 0
  bpmn_io: 0
  breakpoint: 0
  canvas: 0
  captcha: 0
  checklistapi: 0
  ckeditor5: 0
  coffee: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  cva: 0
  dashboard: 0
  datetime: 0
  dblog: 0
  drupal_cms_helper: 0
  drupical: 0
  easy_breadcrumb: 0
  easy_email: 0
  easy_email_override: 0
  eca: 0
  eca_base: 0
  eca_config: 0
  eca_content: 0
  eca_misc: 0
  eca_render: 0
  eca_ui: 0
  eca_user: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  friendlycaptcha: 0
  gin_login: 0
  gin_toolbar: 0
  honeypot: 0
  image: 0
  jquery_ui: 0
  jquery_ui_resizable: 0
  klaro: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  login_emailusername: 0
  mailsystem: 0
  media: 0
  media_file_delete: 0
  media_library: 0
  media_library_bulk_upload: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  modeler_api: 0
  navigation: 0
  navigation_extra_tools: 0
  node: 0
  options: 0
  package_manager: 0
  path: 0
  path_alias: 0
  pgsql: 0
  project_browser: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  sam: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  seo_checklist: 0
  simple_sitemap: 0
  svg_image: 0
  symfony_mailer_lite: 0
  system: 0
  tagify: 0
  tagify_user_list: 0
  taxonomy: 0
  text: 0
  token: 0
  token_or: 0
  trash: 0
  ui_icons: 0
  ui_icons_field: 0
  ui_icons_menu: 0
  ui_icons_picker: 0
  update: 0
  user: 0
  view_password: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  yoast_seo: 0
  pathauto: 1
  selective_better_exposed_filters: 1
  views: 10
theme:
  claro: 0
  gin: 0
  canvas_stark: 0
  easy_email_theme: 0
  byte_theme: 0
