_core:
  default_config_hash: RGedRkFydKZjS0ZJ6vbtZH00KbhYVGsK-ABILHdQLyw
prompt_logging: false
prompt_logging_tags: ''
default_providers:
  chat:
    provider_id: openai
    model_id: gpt-4o-mini
  chat_with_complex_json:
    provider_id: openai
    model_id: gpt-4o-mini
  chat_with_image_vision:
    provider_id: openai
    model_id: gpt-4o-mini
  chat_with_structured_response:
    provider_id: openai
    model_id: gpt-4o-mini
  chat_with_tools:
    provider_id: openai
    model_id: gpt-4o-mini
  embeddings:
    provider_id: gemini
    model_id: models/embedding-001
  moderation:
    provider_id: openai
    model_id: omni-moderation-latest
  speech_to_text:
    provider_id: openai
    model_id: whisper-1
  text_to_image:
    provider_id: openai
    model_id: dall-e-3
  text_to_speech:
    provider_id: openai
    model_id: tts-1-hd
default_vdb_provider: postgres
