control_field_max_length: false
exclude_chunk_from_metadata: false
indexing_options:
  url:
    indexing_option: contextual_content
    max: -1
  field_content:
    indexing_option: main_content
    max: -1
  field_description:
    indexing_option: contextual_content
    max: -1
  title:
    indexing_option: contextual_content
    max: -1
