favicon:
  mimetype: image/svg+xml
  path: 'public://geometric_blue_T.svg'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://geometric_reverse_T.svg'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#1b9ae4'
