_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: f71f44dc-0be9-4693-9b49-fdc65bbeb07e
name: trelvik.net
mail: tom@trelvik.net
slogan: ''
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
